sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t dozeta/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dozeta/docker-react npm run test